### ISSUE TITLE
CSV data

### ISSUE THREAD

**Issue by fzalila** [mannasoumya/grnn#1]
Is it possible please to share the data.csv file? 
I tried to create a csv file with similar data but the parse method returns empty data.

**Comment by mannasoumya** [comment]
Thank you for raising this issue.
I have fixed a bug in parseCSV. **Please take latest clone/pull of the repo and try with your code** . This will be reflected to npmjs later this year.
Please find sample data here : [data.csv](https://github.com/mannasoumya/grnn/files/7490102/data.csv)
